# This is a workflow to run the Build job with a different identity than the main calling
# workflow `attest-build-provenance-slsa3.yml`. It also creates a sub artifact that is signed with this identnty.
# The calling workflow will verify that stub artifact to be sure it was using a github-hosted runner.

on:
  workflow_call:
    inputs:
      build-artifact-name:
        description: The name of GitHub workflow artifact to store the subject files
        default: slsa3_build_artifact
        required: false
        type: string
      subject-path:
        description: >
          Path to the artifact serving as the subject of the attestation. May contain a
          glob pattern or list of paths (total subject count cannot exceed 2500).
          See https://github.com/actions/upload-artifact?tab=readme-ov-file#examples.
        required: true
        type: string
      show-summary:
        description: >
          Whether to attach a list of generated attestations to the workflow run
          summary page. Defaults to true.
        default: true
        required: false
        type: boolean
      build-github-token:
        description: >
          The GitHub token used as environment variable GH_TOKEN to ./slsa_build.sh.
          default: ''
        required: false
        type: string
      build-runner-label:
        description: >
          The runner label to pass to `runs-on:`. e.g., "ubuntu-latest".
        required: true
        type: string
    outputs:
      build-artifact-id:
        description: The artifact-id of the build artifacts. See the `download-artifact` Step for how to use.
        value: ${{ jobs.build-high-perms.outputs.build-artifact-id }}
      stub-artifact-id:
        description: The artifact-id of the stub artifact and bundle attestation file.
        value: ${{ jobs.build-high-perms.outputs.stub-artifact-id }}
      stub-attestation-id:
        description: The artifact-id of the stub artifact's bundle attestation file.
        value: ${{ jobs.build-high-perms.outputs.stub-attestation-id }}

jobs:
  build-high-perms:
    outputs:
      build-artifact-id: ${{ steps.upload-build-artifact.outputs.artifact-id }}
      stub-artifact-id: ${{ steps.upload-stub-artifact.outputs.artifact-id }}
      stub-attestation-id: ${{ steps.upload-stub-attestation.outputs.artifact-id }}
    permissions:
      contents: read
      id-token: write
      attestations: write
    runs-on: ${{ inputs.build-runner-label }}
    steps:
      - name: detect-runner
        if: ${{ runner.environment != 'github-hosted' }}
        run: echo "self-hosted runner detected, failing job!" && exit 1
      - name: checkout-source-repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          ref: ${{ github.sha }}
          persist-credentials: false
      - name: slsa-build
        if: ${{ runner.environment == 'github-hosted' }}
        uses: ./.github/actions/slsa-build
        env:
          GITHUB_TOKEN: ${{ inputs.build-github-token }}
      - name: upload-build-artifact
        id: upload-build-artifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 #v4.6.0
        with:
          name: ${{ inputs.build-artifact-name }}
          path: ${{ inputs.subject-path }}
          if-no-files-found: error
      - name: attest-stub
        if: ${{ runner.environment == 'github-hosted' }}
        id: attest-stub
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
        with:
          subject-path: ${{ github.event_path }}
          show-summary: ${{ inputs.show-summary }}
      - name: upload-stub-artifact
        id: upload-stub-artifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 #v4.6.0
        with:
          name: ${{ inputs.build-artifact-name }}-stub
          path: |
            ${{ github.event_path }}
          if-no-files-found: error
      - name: upload-stub-attestation
        id: upload-stub-attestation
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 #v4.6.0
        with:
            name: ${{ inputs.build-artifact-name }}-stub-attestation
            path: |
                ${{ steps.attest-stub.outputs.bundle-path }}
            if-no-files-found: error
